server:
    port: 8080
spring:
    jpa:
        show-sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: update
    datasource:
        name: datasourceSAPS
        url: jdbc:h2:file:/home/ubuntu/workspace/wsmenuRDS
        username: admin
        password: 
        driver-class-name: org.h2.Driver
swagger:
    enabled: true
